import {
  COMPONENT_TYPES,
  FORM_TYPES,
  PROP_TYPES,
  FIELD_NAME,
  GROUPS,
  Triggers,
  StylesPanelSections,
} from "@draftbit/types";

const SEED_DATA_PROPS = {
  locale: {
    label: "Locale",
    description: "Locale for the datepicker. Must be a valid Locale",
    formType: FORM_TYPES.string,
    propType: PROP_TYPES.STRING,
    defaultValue: "en",
    editable: true,
    required: false,
    group: GROUPS.basic,
  },
  label: {
    label: "Label",
    description: "The label to be displayed on the picker",
    formType: FORM_TYPES.string,
    propType: PROP_TYPES.STRING,
    defaultValue: "Date",
    editable: true,
    required: true,
    group: GROUPS.data,
  },
  calendarIcon: {
    label: "Icon",
    description: "The icon to display on the right",
    formType: FORM_TYPES.icon,
    propType: PROP_TYPES.STRING,
    defaultValue: "calendar",
    editable: true,
    required: false,
    group: GROUPS.basic,
  },
  mode: {
    label: "Mode",
    description: "Choose between date, time and datetime",
    defaultValue: "date",
    editable: true,
    required: false,
    formType: FORM_TYPES.flatArray,
    propType: PROP_TYPES.STRING,
    options: ["outlined", "flat"],
    group: GROUPS.basic,
  },
  disabled: {
    label: "Disabled",
    description:
      "Whether the picker should be disabled. Will prevent selection and show a greyed out state.",
    formType: FORM_TYPES.boolean,
    propType: PROP_TYPES.BOOLEAN,
    defaultValue: false,
    editable: true,
    required: false,
    group: GROUPS.data,
  },
  fieldName: {
    ...FIELD_NAME,
    handlerPropName: "onChange",
    valuePropName: "value",
    defaultValue: "date",
  },
};

export const SEED_DATA = [
  {
    name: "Date Picker Input",
    tag: "DatePickerInput",
    packageName: "react-native-paper-dates",
    description: "A component used to select a date from a visual calendar",
    category: COMPONENT_TYPES.input,
    layout: null,
    triggers: [Triggers.OnDateChange],
    StylesPanelSections: [
      StylesPanelSections.Typography,
      StylesPanelSections.Background,
      StylesPanelSections.Borders,
      StylesPanelSections.MarginsAndPaddings,
      StylesPanelSections.Position,
      StylesPanelSections.Size,
    ],
    props: {
      ...SEED_DATA_PROPS,
      type: {
        label: "Appearance",
        description: "Type of Datepicker",
        formType: FORM_TYPES.flatArray,
        propType: PROP_TYPES.STRING,
        defaultValue: "solid",
        options: ["solid", "underline"],
        editable: true,
        required: true,
        group: GROUPS.basic,
      },
    },
  },
];
