import {
  COMPONENT_TYPES,
  FORM_TYPES,
  BORDER_RADIUS_MODE,
} from "../core/component-types";
export const SEED_DATA = {
  name: "Map",
  tag: "MapSimple",
  description: "A map, with optional markers",
  category: COMPONENT_TYPES.deprecated,
  preview_image_url: "{CLOUDINARY_URL}/Map_Simple.png",
  supports_list_render: false,
  layout: {},
  props: {
    initialLatitude: {
      label: "Initial latitude",
      description:
        "The latitude of the location to center the map on initially",
      formType: FORM_TYPES.number,
      min: -90,
      max: 90,
      step: 1,
      precision: 6,
      defaultValue: 37.402184,
      required: true,
      editable: true,
    },
    initialLongitude: {
      label: "Initial longitude",
      description:
        "The longitude of the location to center the map on initially",
      formType: FORM_TYPES.number,
      min: -180,
      max: 180,
      step: 1,
      precision: 6,
      defaultValue: -122.121264,
      required: true,
      editable: true,
    },
    initialLatitudeDelta: {
      label: "Initial latitude delta",
      description:
        "The amount of latitude to display on the map initially (the horizontal zoom)",
      formType: FORM_TYPES.number,
      min: 0.0001,
      max: 100,
      step: 1,
      precision: 4,
      defaultValue: 0.2,
      required: true,
      editable: true,
    },
    initialLongitudeDelta: {
      label: "Initial longitude delta",
      description:
        "The amount of longitude to display on the map initially (the vertical zoom)",
      formType: FORM_TYPES.number,
      min: 0.0001,
      max: 100,
      step: 1,
      precision: 4,
      defaultValue: 0.2,
      required: true,
      editable: true,
    },
    aspectRatio: {
      label: "Aspect ratio",
      description: "Aspect ratio of the map",
      formType: FORM_TYPES.aspectRatio,
      defaultValue: 1,
      editable: true,
      required: true,
    },
    interactionDisabled: {
      label: "Disable interaction",
      description: "Prevent users from dragging or zooming on the map",
      formType: FORM_TYPES.boolean,
      defaultValue: false,
      editable: true,
      required: false,
    },
    pinColor: {
      label: "Pin color",
      description: "Color of the map pins",
      editable: true,
      required: true,
      defaultValue: "primary",
      formType: FORM_TYPES.color,
    },
    markers: {
      label: "Markers",
      description: "Markers for the map.",
      formType: FORM_TYPES.arrayInput,
      defaultValue: [],
      editable: true,
      required: false,
    },
    borderRadiusMode: BORDER_RADIUS_MODE,
  },
};
